spring:
  shutdown: graceful
  application:
    name: steplogs-logging-agent
  task.scheduling.pool.size: 5

steplogs:
  logging:
    agent:
      server-url: ws://localhost:8080/ 
      app-key: LFgbD1qOsdKOOS4Cqutmb5L2as5EYDNec6BF2sTSv0eTVr2m
      host-id: please-change-to-your-unique-host-id  
      watch-dirs: ./logs
      retry-cycle-timeout: 3600000
      file-idle-timeout: 60000
      file-concurrency: 4

      log-convertor:
        target-dir: ./logs
        watch-dirs: ./log
        seperator: "\n"
        log-date-time-format: yyyy-MM-dd HH:mm:ss.SSS
        log-head: '{"AppNodeConfig":{"version":"1.2.3","hostId":"node-123.test.test","program":"1.2.2-1231321.jar","github":{"commit":"8dd90aef05c25fd89bc92ba74ce70cab6f1f3916","sourcePaths":["src/main/java"],"branch":"main","repository":"repo/test-project"},"internalIp":"12.2.2.2","externalIp":"12.2.2.2","httpHeaderIdType":1,"applicationName":"test-service"},"LoggerConfig":{"fileName":"./logs/test-service","printFile":true,"printStdout":true,"logAsync":true,"logVersion":null,"logLight":true,"logDateTimeFormat":"yyyy-MM-dd HH:mm:ss.SSS","fileMaxLength":536870912,"logSanitizerPatterns":["/JSON/*.*Service*#*/*/SKIP(appKey|encryptionKey|password|sessionId)","/JSON/*Service*/*/MD5$1(longText)"]}}'

        extractor: 
          time: "^(\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}[+-]\\d{2}:\\d{2})"
          time_parser: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
          thread-info: "--- \\[.*\\]\\s*\\[(.*?)\\]\\s+"
          step: "--- \\[.*\\]\\s*\\[.*\\]\\s+(.*?)\\s+:"

logging: # log4j
  file.name: log/${spring.application.name}.log
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  level: 
    root: DEBUG